# Generated by Django 5.2.17 on 2026-09-06 07:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coverage_key', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'dataset',
            },
        ),
        migrations.CreateModel(
            name='DatasetMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dataset_membership',
            },
        ),
        migrations.CreateModel(
            name='DatasetRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'dataset_revision',
            },
        ),
        migrations.CreateModel(
            name='FileArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(max_length=240, unique=True)),
                ('physical_hash', models.CharField(max_length=64)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('byte_size', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'file_artifact',
            },
        ),
        migrations.CreateModel(
            name='IngestionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('RECEIVED', 'Received'), ('PARSING', 'Parsing'), ('READY', 'Ready'), ('REJECTED', 'Rejected'), ('ACTIVATED', 'Activated'), ('NO_CHANGE', 'No change'), ('REPLAYED', 'Historical replay')], default='RECEIVED', max_length=10)),
                ('physical_hash', models.CharField(max_length=64)),
                ('semantic_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('delimiter', models.CharField(max_length=1)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingestion_attempt',
            },
        ),
        migrations.CreateModel(
            name='LogicalTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_record_key', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'logical_transaction',
            },
        ),
        migrations.CreateModel(
            name='RawRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('raw_values', models.JSONField()),
                ('canonical_preview', models.JSONField(blank=True, null=True)),
                ('validation', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'raw_row',
            },
        ),
        migrations.CreateModel(
            name='TransactionObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_reference', models.CharField(blank=True, max_length=240, null=True)),
                ('executed_at_utc', models.DateTimeField()),
                ('instrument', models.CharField(max_length=120)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=12, max_digits=38)),
                ('unit_price', models.DecimalField(decimal_places=12, max_digits=38)),
                ('gross_amount', models.DecimalField(decimal_places=12, max_digits=38)),
                ('currency', models.CharField(max_length=12)),
                ('state', models.CharField(choices=[('SETTLED', 'Settled'), ('CANCELLED', 'Cancelled')], max_length=9)),
                ('eligible_for_matching', models.BooleanField()),
                ('provenance', models.JSONField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'transaction_observation',
            },
        ),
    ]
