# Generated by Django 5.2.17 on 2026-09-06 07:32

import django.db.models.deletion
import reconciliation.domain.ingestion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('sources', '0001_initial'),
        ('workspaces', '0002_workspace_cleanup_and_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='book_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='sources.booksource'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='datasetmembership',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_memberships', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='datasetrevision',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='ingestion.dataset'),
        ),
        migrations.AddField(
            model_name='datasetrevision',
            name='parent_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='ingestion.datasetrevision'),
        ),
        migrations.AddField(
            model_name='datasetrevision',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_revisions', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='datasetmembership',
            name='dataset_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ingestion.datasetrevision'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for', to='ingestion.datasetrevision'),
        ),
        migrations.AddField(
            model_name='fileartifact',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_artifacts', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='ingestionattempt',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='ingestion.fileartifact'),
        ),
        migrations.AddField(
            model_name='ingestionattempt',
            name='contract_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='sources.sourcecontractrevision'),
        ),
        migrations.AddField(
            model_name='ingestionattempt',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ingestion.dataset'),
        ),
        migrations.AddField(
            model_name='ingestionattempt',
            name='expected_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependent_attempts', to='ingestion.datasetrevision'),
        ),
        migrations.AddField(
            model_name='ingestionattempt',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_attempts', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='datasetrevision',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='activated_revision', to='ingestion.ingestionattempt'),
        ),
        migrations.AddField(
            model_name='logicaltransaction',
            name='book_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logical_transactions', to='sources.booksource'),
        ),
        migrations.AddField(
            model_name='logicaltransaction',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logical_transactions', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='datasetmembership',
            name='logical_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='ingestion.logicaltransaction'),
        ),
        migrations.AddField(
            model_name='rawrow',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_rows', to='ingestion.ingestionattempt'),
        ),
        migrations.AddField(
            model_name='rawrow',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_rows', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='transactionobservation',
            name='logical_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='ingestion.logicaltransaction'),
        ),
        migrations.AddField(
            model_name='transactionobservation',
            name='raw_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='ingestion.rawrow'),
        ),
        migrations.AddField(
            model_name='transactionobservation',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_observations', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='datasetmembership',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='ingestion.transactionobservation'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['workspace', 'book_source'], name='dataset_workspace_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='dataset',
            constraint=models.UniqueConstraint(fields=('book_source', 'coverage_key'), name='dataset_source_coverage_unique'),
        ),
        migrations.AddIndex(
            model_name='fileartifact',
            index=models.Index(fields=['workspace', 'physical_hash'], name='artifact_workspace_hash_idx'),
        ),
        migrations.AddConstraint(
            model_name='fileartifact',
            constraint=models.CheckConstraint(condition=models.Q(('byte_size__gte', 0)), name='artifact_size_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='ingestionattempt',
            index=models.Index(fields=['workspace', 'dataset', 'created_at'], name='attempt_workspace_dataset_idx'),
        ),
        migrations.AddConstraint(
            model_name='ingestionattempt',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['RECEIVED', 'PARSING', 'READY', 'REJECTED', 'ACTIVATED', 'NO_CHANGE', 'REPLAYED'])), name='attempt_valid_state'),
        ),
        migrations.AddIndex(
            model_name='datasetrevision',
            index=models.Index(fields=['workspace', 'dataset', 'created_at'], name='revision_workspace_dataset_idx'),
        ),
        migrations.AddConstraint(
            model_name='logicaltransaction',
            constraint=models.UniqueConstraint(fields=('book_source', 'source_record_key'), name='logical_source_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='logicaltransaction',
            constraint=models.CheckConstraint(condition=models.Q(('source_record_key', ''), _negated=True), name='logical_source_key_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='rawrow',
            constraint=models.UniqueConstraint(fields=('attempt', 'row_number'), name='raw_row_attempt_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='rawrow',
            constraint=models.CheckConstraint(condition=models.Q(('row_number__gte', 1)), name='raw_row_number_positive'),
        ),
        migrations.AddIndex(
            model_name='transactionobservation',
            index=models.Index(fields=['workspace', 'logical_transaction'], name='obs_ws_logical_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionobservation',
            index=models.Index(fields=['workspace', 'instrument', 'side', 'currency', 'executed_at_utc'], name='observation_candidate_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactionobservation',
            constraint=models.CheckConstraint(condition=models.Q(('side__in', ['BUY', 'SELL'])), name='observation_valid_side'),
        ),
        migrations.AddConstraint(
            model_name='transactionobservation',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['SETTLED', 'CANCELLED'])), name='observation_valid_state'),
        ),
        migrations.AddConstraint(
            model_name='transactionobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('eligible_for_matching', False), ('state', reconciliation.domain.ingestion.CanonicalState['CANCELLED'])), models.Q(('eligible_for_matching', True), ('state', reconciliation.domain.ingestion.CanonicalState['SETTLED'])), _connector='OR'), name='observation_state_eligibility'),
        ),
        migrations.AddIndex(
            model_name='datasetmembership',
            index=models.Index(fields=['workspace', 'dataset_revision'], name='membership_ws_revision_idx'),
        ),
        migrations.AddConstraint(
            model_name='datasetmembership',
            constraint=models.UniqueConstraint(fields=('dataset_revision', 'logical_transaction'), name='membership_revision_logical_unique'),
        ),
    ]
