# Generated by Django 5.2.17 on 2026-09-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionattempt',
            name='validation',
            field=models.JSONField(default=list),
        ),
    ]
