# Generated by Django 5.2.17 on 2026-09-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_ingestionattempt_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionattempt',
            name='activation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
