# Generated by Django 5.2.17 on 2026-09-08 09:06

import django.db.models.deletion
import reconciliation.domain.jobs
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0004_ingestionattempt_activation_reason'),
        ('reconciliation', '0004_reconciliationrun_progress'),
        ('workspaces', '0002_workspace_cleanup_and_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('IMPORT_VALIDATION', 'Import_Validation'), ('RECONCILIATION_RUN', 'Reconciliation_Run'), ('WORKSPACE_CLEANUP', 'Workspace_Cleanup')], max_length=20)),
                ('state', models.CharField(choices=[('READY', 'Ready'), ('LEASED', 'Leased'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default=reconciliation.domain.jobs.JobState['READY'], max_length=9)),
                ('available_at', models.DateTimeField()),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('current_token', models.CharField(blank=True, max_length=64, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('cleanup_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_item', to='workspaces.workspacecleanuprequest')),
                ('import_attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_item', to='ingestion.ingestionattempt')),
                ('reconciliation_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_item', to='reconciliation.reconciliationrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'work_item',
            },
        ),
        migrations.CreateModel(
            name='JobAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('leased_at', models.DateTimeField()),
                ('lease_until', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], max_length=9, null=True)),
                ('failure_category', models.CharField(blank=True, choices=[('TRANSIENT', 'Transient'), ('PERMANENT', 'Permanent')], max_length=9, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_attempts', to='workspaces.workspace')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='jobs.workitem')),
            ],
            options={
                'db_table': 'job_attempt',
            },
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['kind', 'state', 'available_at'], name='work_item_claim_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['workspace', 'kind'], name='work_item_workspace_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='workitem',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['IMPORT_VALIDATION', 'RECONCILIATION_RUN', 'WORKSPACE_CLEANUP'])), name='work_item_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='workitem',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['READY', 'LEASED', 'SUCCEEDED', 'FAILED'])), name='work_item_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='workitem',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='work_item_max_attempts_positive'),
        ),
        migrations.AddConstraint(
            model_name='workitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cleanup_request__isnull', True), ('import_attempt__isnull', False), ('kind', reconciliation.domain.jobs.JobKind['IMPORT_VALIDATION']), ('reconciliation_run__isnull', True)), models.Q(('cleanup_request__isnull', True), ('import_attempt__isnull', True), ('kind', reconciliation.domain.jobs.JobKind['RECONCILIATION_RUN']), ('reconciliation_run__isnull', False)), models.Q(('cleanup_request__isnull', False), ('import_attempt__isnull', True), ('kind', reconciliation.domain.jobs.JobKind['WORKSPACE_CLEANUP']), ('reconciliation_run__isnull', True)), _connector='OR'), name='work_item_target_shape_valid'),
        ),
        migrations.AddConstraint(
            model_name='workitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('current_token__isnull', False), ('lease_until__isnull', False), ('state', reconciliation.domain.jobs.JobState['LEASED'])), models.Q(('current_token__isnull', True), ('lease_until__isnull', True), ('state__in', [reconciliation.domain.jobs.JobState['READY'], reconciliation.domain.jobs.JobState['SUCCEEDED'], reconciliation.domain.jobs.JobState['FAILED']])), _connector='OR'), name='work_item_lease_shape_valid'),
        ),
        migrations.AddIndex(
            model_name='jobattempt',
            index=models.Index(fields=['workspace', 'work_item', 'leased_at'], name='job_attempt_work_item_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobattempt',
            constraint=models.CheckConstraint(condition=models.Q(('lease_until__gt', models.F('leased_at'))), name='job_attempt_lease_after_grant'),
        ),
        migrations.AddConstraint(
            model_name='jobattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('failure_category__isnull', True), ('outcome__isnull', True)), models.Q(('completed_at__isnull', False), ('failure_category__isnull', True), ('outcome__in', ['SUCCEEDED', 'EXPIRED'])), models.Q(('completed_at__isnull', False), ('failure_category__isnull', False), ('outcome', 'FAILED')), _connector='OR'), name='job_attempt_outcome_shape_valid'),
        ),
    ]
