# Generated by Django 5.2.17 on 2026-09-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('worker_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'worker_heartbeat',
            },
        ),
    ]
