# Generated by Django 5.2.17 on 2026-09-07 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('ingestion', '0004_ingestionattempt_activation_reason'),
        ('workspaces', '0002_workspace_cleanup_and_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('matching_policy', models.JSONField()),
                ('comparison_policy', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'policy_revision',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coverage_key', models.CharField(max_length=200)),
                ('generation', models.PositiveBigIntegerField(default=0)),
                ('is_dirty', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'reconciliation_scope',
            },
        ),
        migrations.AddField(
            model_name='reconciliationbook',
            name='generation',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationbook',
            name='resolution_generation',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='reconciliationbook',
            constraint=models.CheckConstraint(condition=models.Q(('generation__gte', 0)), name='book_generation_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationbook',
            constraint=models.CheckConstraint(condition=models.Q(('resolution_generation__gte', 0)), name='book_resolution_gen_nonnegative'),
        ),
        migrations.AddField(
            model_name='policyrevision',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_revisions', to='books.reconciliationbook'),
        ),
        migrations.AddField(
            model_name='policyrevision',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_revisions', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='reconciliationscope',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='books.reconciliationbook'),
        ),
        migrations.AddField(
            model_name='reconciliationscope',
            name='left_dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='left_reconciliation_scopes', to='ingestion.dataset'),
        ),
        migrations.AddField(
            model_name='reconciliationscope',
            name='right_dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='right_reconciliation_scopes', to='ingestion.dataset'),
        ),
        migrations.AddField(
            model_name='reconciliationscope',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_scopes', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='policyrevision',
            index=models.Index(fields=['workspace', 'book', 'revision'], name='policy_workspace_book_idx'),
        ),
        migrations.AddConstraint(
            model_name='policyrevision',
            constraint=models.UniqueConstraint(fields=('book', 'revision'), name='policy_book_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='policyrevision',
            constraint=models.UniqueConstraint(fields=('book', 'digest'), name='policy_book_digest_unique'),
        ),
        migrations.AddConstraint(
            model_name='policyrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='policy_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='policyrevision',
            constraint=models.CheckConstraint(condition=models.Q(('digest', ''), _negated=True), name='policy_digest_nonempty'),
        ),
        migrations.AddIndex(
            model_name='reconciliationscope',
            index=models.Index(fields=['workspace', 'book', 'coverage_key'], name='scope_workspace_book_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationscope',
            index=models.Index(fields=['workspace', 'is_dirty'], name='scope_workspace_dirty_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationscope',
            constraint=models.UniqueConstraint(fields=('book', 'coverage_key'), name='scope_book_coverage_unique'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationscope',
            constraint=models.CheckConstraint(condition=models.Q(('coverage_key', ''), _negated=True), name='scope_coverage_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationscope',
            constraint=models.CheckConstraint(condition=models.Q(('left_dataset', models.F('right_dataset')), _negated=True), name='scope_datasets_distinct'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationscope',
            constraint=models.CheckConstraint(condition=models.Q(('generation__gte', 0)), name='scope_generation_nonnegative'),
        ),
    ]
