# Generated by Django 5.2.17 on 2026-09-07 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_policyrevision_reconciliationscope_and_more'),
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationscope',
            name='current_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_scopes', to='reconciliation.reconciliationrun'),
        ),
    ]
