# Generated by Django 5.2.17 on 2026-09-07 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_reconciliationscope_current_run'),
        ('reconciliation', '0003_remove_rundiagnostic_candidate_current_pair_observation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationscope',
            name='current_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_scopes', to='reconciliation.reconciliationrun'),
        ),
    ]
