# Generated by Django 5.2.17 on 2026-09-07 16:28

import django.db.models.deletion
import reconciliation.domain.review
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0004_alter_reconciliationscope_current_run'),
        ('ingestion', '0004_ingestionattempt_activation_reason'),
        ('reconciliation', '0003_remove_rundiagnostic_candidate_current_pair_observation_and_more'),
        ('workspaces', '0002_workspace_cleanup_and_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_kind', models.CharField(choices=[('PAIR', 'Pair'), ('UNPAIRED', 'Unpaired'), ('AMBIGUITY', 'Ambiguity')], max_length=10)),
                ('state_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_occurrences', to='reconciliation.assignmentcomponent')),
                ('pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_occurrences', to='reconciliation.runpair')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_occurrences', to='reconciliation.reconciliationrun')),
                ('unpaired', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_occurrences', to='reconciliation.rununpaired')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_occurrences', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'case_occurrence',
            },
        ),
        migrations.CreateModel(
            name='InvestigationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('PAIR', 'Pair'), ('UNPAIRED', 'Unpaired'), ('AMBIGUITY', 'Ambiguity')], max_length=10)),
                ('stable_key', models.CharField(max_length=80)),
                ('digest', models.CharField(max_length=64)),
                ('record_side', models.CharField(blank=True, choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=5, null=True)),
                ('ambiguity_left_logical_ids', models.JSONField(blank=True, null=True)),
                ('ambiguity_right_logical_ids', models.JSONField(blank=True, null=True)),
                ('policy_digest', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField()),
                ('ambiguity_scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambiguity_cases', to='books.reconciliationscope')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_cases', to='books.reconciliationbook')),
                ('left_logical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pair_cases_as_left', to='ingestion.logicaltransaction')),
                ('record_logical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unpaired_cases', to='ingestion.logicaltransaction')),
                ('right_logical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pair_cases_as_right', to='ingestion.logicaltransaction')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_cases', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'investigation_case',
            },
        ),
        migrations.CreateModel(
            name='CaseScopeProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_health', models.CharField(blank=True, choices=[('UNCHANGED', 'Unchanged'), ('EVIDENCE_CHANGED', 'Evidence_Changed'), ('PARTNER_UNAVAILABLE', 'Partner_Unavailable'), ('NEW_CANDIDATE', 'New_Candidate')], max_length=20, null=True)),
                ('attention', models.JSONField(default=list)),
                ('applied_data_generation', models.PositiveBigIntegerField()),
                ('applied_resolution_generation', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField()),
                ('current_occurrence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_projection', to='cases.caseoccurrence')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_projections', to='reconciliation.reconciliationrun')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_projections', to='books.reconciliationscope')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_scope_projections', to='workspaces.workspace')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_projections', to='cases.investigationcase')),
            ],
            options={
                'db_table': 'case_scope_projection',
            },
        ),
        migrations.AddField(
            model_name='caseoccurrence',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='cases.investigationcase'),
        ),
        migrations.AddIndex(
            model_name='investigationcase',
            index=models.Index(fields=['workspace', 'book', 'kind', 'created_at'], name='case_workspace_book_idx'),
        ),
        migrations.AddConstraint(
            model_name='investigationcase',
            constraint=models.UniqueConstraint(fields=('book', 'stable_key'), name='case_book_stable_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='investigationcase',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['PAIR', 'UNPAIRED', 'AMBIGUITY'])), name='case_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='investigationcase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ambiguity_scope__isnull', True), ('kind', reconciliation.domain.review.CaseKind['PAIR']), ('left_logical__isnull', False), ('policy_digest__isnull', True), ('record_logical__isnull', True), ('record_side__isnull', True), ('right_logical__isnull', False)), models.Q(('ambiguity_scope__isnull', True), ('kind', reconciliation.domain.review.CaseKind['UNPAIRED']), ('left_logical__isnull', True), ('policy_digest__isnull', True), ('record_logical__isnull', False), ('record_side__in', ['LEFT', 'RIGHT']), ('right_logical__isnull', True)), models.Q(('ambiguity_scope__isnull', False), ('kind', reconciliation.domain.review.CaseKind['AMBIGUITY']), ('left_logical__isnull', True), ('policy_digest__isnull', False), ('record_logical__isnull', True), ('record_side__isnull', True), ('right_logical__isnull', True)), _connector='OR'), name='case_identity_shape_valid'),
        ),
        migrations.AddIndex(
            model_name='casescopeprojection',
            index=models.Index(fields=['workspace', 'scope', 'review_health'], name='case_projection_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='casescopeprojection',
            constraint=models.UniqueConstraint(fields=('case', 'scope'), name='case_scope_projection_unique'),
        ),
        migrations.AddIndex(
            model_name='caseoccurrence',
            index=models.Index(fields=['workspace', 'case', 'created_at'], name='occurrence_case_idx'),
        ),
        migrations.AddConstraint(
            model_name='caseoccurrence',
            constraint=models.UniqueConstraint(fields=('case', 'run'), name='case_run_occurrence_unique'),
        ),
        migrations.AddConstraint(
            model_name='caseoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('component__isnull', True), ('pair__isnull', False), ('result_kind', reconciliation.domain.review.CaseResultKind['PAIR']), ('unpaired__isnull', True)), models.Q(('component__isnull', True), ('pair__isnull', True), ('result_kind', reconciliation.domain.review.CaseResultKind['UNPAIRED']), ('unpaired__isnull', False)), models.Q(('component__isnull', False), ('pair__isnull', True), ('result_kind', reconciliation.domain.review.CaseResultKind['AMBIGUITY']), ('unpaired__isnull', True)), _connector='OR'), name='occurrence_result_shape_valid'),
        ),
    ]
