# Generated by Django 5.2.17 on 2026-09-07 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_reconciliationscope_current_run'),
        ('cases', '0001_initial'),
        ('reconciliation', '0003_remove_rundiagnostic_candidate_current_pair_observation_and_more'),
        ('workspaces', '0002_workspace_cleanup_and_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseLineage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transition_kind', models.CharField(default='PREDECESSOR_OF', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('caused_by_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_lineage', to='reconciliation.reconciliationrun')),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_edges', to='cases.investigationcase')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_lineage', to='books.reconciliationscope')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_edges', to='cases.investigationcase')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_lineage', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'case_lineage',
                'indexes': [models.Index(fields=['workspace', 'scope', 'caused_by_run'], name='case_lineage_scope_idx')],
                'constraints': [models.UniqueConstraint(fields=('predecessor', 'successor', 'caused_by_run'), name='case_lineage_run_edge_unique'), models.CheckConstraint(condition=models.Q(('predecessor', models.F('successor')), _negated=True), name='case_lineage_not_self'), models.CheckConstraint(condition=models.Q(('transition_kind', 'PREDECESSOR_OF')), name='case_lineage_kind_valid')],
            },
        ),
    ]
