# Generated by Django 5.2.17 on 2026-09-07 16:42

import reconciliation.domain.review
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_reconciliationscope_current_run'),
        ('cases', '0002_caselineage'),
        ('ingestion', '0004_ingestionattempt_activation_reason'),
        ('workspaces', '0002_workspace_cleanup_and_lifecycle'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='investigationcase',
            name='case_identity_shape_valid',
        ),
        migrations.AddConstraint(
            model_name='investigationcase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ambiguity_left_logical_ids__isnull', True), ('ambiguity_right_logical_ids__isnull', True), ('ambiguity_scope__isnull', True), ('kind', reconciliation.domain.review.CaseKind['PAIR']), ('left_logical__isnull', False), ('policy_digest__isnull', True), ('record_logical__isnull', True), ('record_side__isnull', True), ('right_logical__isnull', False)), models.Q(('ambiguity_left_logical_ids__isnull', True), ('ambiguity_right_logical_ids__isnull', True), ('ambiguity_scope__isnull', True), ('kind', reconciliation.domain.review.CaseKind['UNPAIRED']), ('left_logical__isnull', True), ('policy_digest__isnull', True), ('record_logical__isnull', False), ('record_side__in', ['LEFT', 'RIGHT']), ('right_logical__isnull', True)), models.Q(('ambiguity_left_logical_ids__isnull', False), ('ambiguity_right_logical_ids__isnull', False), ('ambiguity_scope__isnull', False), ('kind', reconciliation.domain.review.CaseKind['AMBIGUITY']), ('left_logical__isnull', True), ('policy_digest__isnull', False), ('record_logical__isnull', True), ('record_side__isnull', True), ('right_logical__isnull', True)), _connector='OR'), name='case_identity_shape_valid'),
        ),
        migrations.AddConstraint(
            model_name='investigationcase',
            constraint=models.CheckConstraint(condition=models.Q(('left_logical', models.F('right_logical')), _negated=True), name='case_pair_endpoints_distinct'),
        ),
    ]
