# Generated by Django 5.2.17 on 2026-09-07 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_policyrevision_reconciliationscope_and_more'),
        ('ingestion', '0004_ingestionattempt_activation_reason'),
        ('resolutions', '0001_initial'),
        ('workspaces', '0002_workspace_cleanup_and_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_key', models.CharField(max_length=64)),
                ('graph_digest', models.CharField(max_length=64)),
                ('solver_version', models.CharField(max_length=100)),
                ('left_observation_ids', models.JSONField()),
                ('right_observation_ids', models.JSONField()),
                ('candidate_count', models.PositiveIntegerField()),
                ('optimal_utility_bp', models.PositiveIntegerField()),
                ('complete', models.BooleanField()),
                ('limit_reason', models.CharField(blank=True, max_length=80, null=True)),
                ('proposals', models.JSONField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_components', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'assignment_component',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manifest', models.JSONField()),
                ('manifest_hash', models.CharField(max_length=64)),
                ('data_generation', models.PositiveBigIntegerField()),
                ('resolution_generation', models.PositiveBigIntegerField()),
                ('scope_generation', models.PositiveBigIntegerField()),
                ('engine_version', models.CharField(max_length=80)),
                ('solver_version', models.CharField(max_length=100)),
                ('lifecycle', models.CharField(choices=[('FROZEN', 'Frozen'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='FROZEN', max_length=10)),
                ('freshness', models.CharField(choices=[('PENDING', 'Pending'), ('CURRENT', 'Current'), ('STALE', 'Stale')], default='PENDING', max_length=8)),
                ('result_digest', models.CharField(blank=True, max_length=64, null=True)),
                ('result_counts', models.JSONField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('left_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs_as_left', to='ingestion.datasetrevision')),
                ('policy_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='books.policyrevision')),
                ('right_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs_as_right', to='ingestion.datasetrevision')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='books.reconciliationscope')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_runs', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'reconciliation_run',
            },
        ),
        migrations.CreateModel(
            name='CandidateEvidence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('blocking_reasons', models.JSONField()),
                ('features', models.JSONField()),
                ('contradictions', models.JSONField()),
                ('coverage_failures', models.JSONField()),
                ('coverage_sufficient', models.BooleanField()),
                ('complete_computation', models.BooleanField()),
                ('score_bp', models.PositiveIntegerField()),
                ('score_label', models.CharField(max_length=40)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='reconciliation.assignmentcomponent')),
                ('left_observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_evidence_as_left', to='ingestion.transactionobservation')),
                ('right_observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_evidence_as_right', to='ingestion.transactionobservation')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_evidence', to='workspaces.workspace')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='reconciliation.reconciliationrun')),
            ],
            options={
                'db_table': 'candidate_evidence',
            },
        ),
        migrations.AddField(
            model_name='assignmentcomponent',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='reconciliation.reconciliationrun'),
        ),
        migrations.CreateModel(
            name='RunDecisionInput',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('decision_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_inputs', to='resolutions.decisionrevision')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_inputs', to='reconciliation.reconciliationrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_decision_inputs', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'run_decision_input',
            },
        ),
        migrations.CreateModel(
            name='RunDiagnostic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('ACCEPTED_UNMATCHED_CANDIDATE', 'Accepted_Unmatched_Candidate'), ('INCOMPLETE_SEARCH', 'Incomplete_Search')], max_length=32)),
                ('complete', models.BooleanField()),
                ('explanation', models.TextField()),
                ('candidate_current_pair_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnostics_as_allocation', to='ingestion.transactionobservation')),
                ('candidate_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnostics_as_candidate', to='ingestion.transactionobservation')),
                ('decision_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='run_diagnostics', to='resolutions.decisionrevision')),
                ('record_observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostics_as_record', to='ingestion.transactionobservation')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='reconciliation.reconciliationrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_diagnostics', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'run_diagnostic',
            },
        ),
        migrations.CreateModel(
            name='RunInput',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=5)),
                ('logical_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_inputs', to='ingestion.logicaltransaction')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_inputs', to='ingestion.transactionobservation')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='reconciliation.reconciliationrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_inputs', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'run_input',
            },
        ),
        migrations.CreateModel(
            name='RunPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTHORITATIVE_REFERENCE', 'Authoritative_Reference'), ('WEIGHTED_GLOBAL', 'Weighted_Global')], max_length=24)),
                ('reference_value', models.CharField(blank=True, max_length=240, null=True)),
                ('score_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('global_gap_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('explanation', models.TextField()),
                ('decision_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='run_pairs', to='resolutions.decisionrevision')),
                ('left_logical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_pairs_as_left', to='ingestion.logicaltransaction')),
                ('left_observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_pairs_as_left', to='ingestion.transactionobservation')),
                ('right_logical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_pairs_as_right', to='ingestion.logicaltransaction')),
                ('right_observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_pairs_as_right', to='ingestion.transactionobservation')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='reconciliation.reconciliationrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_pairs', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'run_pair',
            },
        ),
        migrations.CreateModel(
            name='FieldComparison',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('EXACT', 'Exact'), ('WITHIN_TOLERANCE', 'Within_Tolerance'), ('DISCREPANT', 'Discrepant'), ('NOT_COMPARABLE', 'Not_Comparable'), ('MISSING', 'Missing')], max_length=20)),
                ('left_value', models.JSONField(null=True)),
                ('right_value', models.JSONField(null=True)),
                ('signed_difference', models.JSONField(null=True)),
                ('allowed_difference', models.JSONField(null=True)),
                ('explanation', models.TextField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_comparisons', to='workspaces.workspace')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='reconciliation.runpair')),
            ],
            options={
                'db_table': 'field_comparison',
            },
        ),
        migrations.CreateModel(
            name='RunUnpaired',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=5)),
                ('reason', models.CharField(choices=[('ACCEPTED_UNMATCHED', 'Accepted_Unmatched'), ('CANCELLED_EXCLUDED', 'Cancelled_Excluded'), ('REVIEWER_RESERVED', 'Reviewer_Reserved'), ('MANUAL_ATTENTION', 'Manual_Attention'), ('DUPLICATE_REFERENCE', 'Duplicate_Reference'), ('PROHIBITED', 'Prohibited'), ('NO_CANDIDATE', 'No_Candidate'), ('BELOW_ASSIGNMENT_FLOOR', 'Below_Assignment_Floor'), ('AMBIGUOUS', 'Ambiguous'), ('COMPUTATION_LIMITED', 'Computation_Limited')], max_length=32)),
                ('explanation', models.TextField()),
                ('related_observation_ids', models.JSONField()),
                ('logical_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_unpaired', to='ingestion.logicaltransaction')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_unpaired', to='ingestion.transactionobservation')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unpaired', to='reconciliation.reconciliationrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_unpaired', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'run_unpaired',
            },
        ),
        migrations.AddIndex(
            model_name='reconciliationrun',
            index=models.Index(fields=['workspace', 'scope', 'created_at'], name='run_workspace_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrun',
            index=models.Index(fields=['workspace', 'lifecycle'], name='run_workspace_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationrun',
            constraint=models.UniqueConstraint(fields=('scope', 'manifest_hash'), name='run_scope_manifest_unique'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationrun',
            constraint=models.CheckConstraint(condition=models.Q(('lifecycle__in', ['FROZEN', 'RUNNING', 'COMPLETED', 'FAILED'])), name='run_lifecycle_valid'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationrun',
            constraint=models.CheckConstraint(condition=models.Q(('freshness__in', ['PENDING', 'CURRENT', 'STALE'])), name='run_freshness_valid'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationrun',
            constraint=models.CheckConstraint(condition=models.Q(('left_revision', models.F('right_revision')), _negated=True), name='run_revisions_distinct'),
        ),
        migrations.AddConstraint(
            model_name='candidateevidence',
            constraint=models.UniqueConstraint(fields=('run', 'left_observation', 'right_observation'), name='run_candidate_edge_unique'),
        ),
        migrations.AddConstraint(
            model_name='assignmentcomponent',
            constraint=models.UniqueConstraint(fields=('run', 'component_key'), name='run_component_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='rundecisioninput',
            constraint=models.UniqueConstraint(fields=('run', 'decision_revision'), name='run_decision_input_unique'),
        ),
        migrations.AddConstraint(
            model_name='rundiagnostic',
            constraint=models.UniqueConstraint(fields=('run', 'record_observation', 'candidate_observation', 'kind'), name='run_diagnostic_unique'),
        ),
        migrations.AddConstraint(
            model_name='rundiagnostic',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['ACCEPTED_UNMATCHED_CANDIDATE', 'INCOMPLETE_SEARCH'])), name='run_diagnostic_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='runinput',
            constraint=models.UniqueConstraint(fields=('run', 'logical_transaction'), name='run_input_logical_unique'),
        ),
        migrations.AddConstraint(
            model_name='runinput',
            constraint=models.UniqueConstraint(fields=('run', 'observation'), name='run_input_observation_unique'),
        ),
        migrations.AddConstraint(
            model_name='runinput',
            constraint=models.CheckConstraint(condition=models.Q(('side__in', ['LEFT', 'RIGHT'])), name='run_input_side_valid'),
        ),
        migrations.AddConstraint(
            model_name='runpair',
            constraint=models.UniqueConstraint(fields=('run', 'left_observation'), name='run_pair_left_unique'),
        ),
        migrations.AddConstraint(
            model_name='runpair',
            constraint=models.UniqueConstraint(fields=('run', 'right_observation'), name='run_pair_right_unique'),
        ),
        migrations.AddConstraint(
            model_name='runpair',
            constraint=models.CheckConstraint(condition=models.Q(('origin__in', ['MANUAL', 'AUTHORITATIVE_REFERENCE', 'WEIGHTED_GLOBAL'])), name='run_pair_origin_valid'),
        ),
        migrations.AddConstraint(
            model_name='fieldcomparison',
            constraint=models.UniqueConstraint(fields=('pair', 'field'), name='pair_comparison_field_unique'),
        ),
        migrations.AddConstraint(
            model_name='rununpaired',
            constraint=models.UniqueConstraint(fields=('run', 'observation'), name='run_unpaired_observation_unique'),
        ),
        migrations.AddConstraint(
            model_name='rununpaired',
            constraint=models.CheckConstraint(condition=models.Q(('side__in', ['LEFT', 'RIGHT'])), name='run_unpaired_side_valid'),
        ),
        migrations.AddConstraint(
            model_name='rununpaired',
            constraint=models.CheckConstraint(condition=models.Q(('reason__in', ['ACCEPTED_UNMATCHED', 'CANCELLED_EXCLUDED', 'REVIEWER_RESERVED', 'MANUAL_ATTENTION', 'DUPLICATE_REFERENCE', 'PROHIBITED', 'NO_CANDIDATE', 'BELOW_ASSIGNMENT_FLOOR', 'AMBIGUOUS', 'COMPUTATION_LIMITED'])), name='run_unpaired_reason_valid'),
        ),
    ]
