# Generated by Django 5.2.17 on 2026-09-07 15:51

import reconciliation.domain.reconciliation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_reconciliationscope_current_run'),
        ('ingestion', '0004_ingestionattempt_activation_reason'),
        ('reconciliation', '0001_initial'),
        ('resolutions', '0001_initial'),
        ('workspaces', '0002_workspace_cleanup_and_lifecycle'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assignmentcomponent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('complete', True), ('limit_reason__isnull', True)), models.Q(('complete', False), ('limit_reason__isnull', False)), _connector='OR'), name='component_limit_shape_valid'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('failure_code__isnull', True), ('freshness__in', ['CURRENT', 'STALE']), ('lifecycle', 'COMPLETED'), ('result_counts__isnull', False), ('result_digest__isnull', False)), models.Q(('completed_at__isnull', True), ('failure_code__isnull', True), ('freshness', 'PENDING'), ('lifecycle__in', ['FROZEN', 'RUNNING']), ('result_counts__isnull', True), ('result_digest__isnull', True)), models.Q(('completed_at__isnull', True), ('failure_code__isnull', False), ('freshness', 'PENDING'), ('lifecycle', 'FAILED'), ('result_counts__isnull', True), ('result_digest__isnull', True)), _connector='OR'), name='run_state_shape_valid'),
        ),
        migrations.AddConstraint(
            model_name='runpair',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('global_gap_bp__isnull', False), ('origin', reconciliation.domain.reconciliation.PairOrigin['WEIGHTED_GLOBAL']), ('score_bp__isnull', False)), models.Q(('global_gap_bp__isnull', True), ('origin__in', [reconciliation.domain.reconciliation.PairOrigin['MANUAL'], reconciliation.domain.reconciliation.PairOrigin['AUTHORITATIVE_REFERENCE']]), ('score_bp__isnull', True)), _connector='OR'), name='run_pair_score_shape_valid'),
        ),
    ]
