# Generated by Django 5.2.17 on 2026-09-07 16:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_reconciliationscope_current_run'),
        ('reconciliation', '0002_assignmentcomponent_component_limit_shape_valid_and_more'),
        ('resolutions', '0001_initial'),
        ('workspaces', '0002_workspace_cleanup_and_lifecycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rundiagnostic',
            name='candidate_current_pair_observation',
        ),
        migrations.AddField(
            model_name='rundiagnostic',
            name='candidate_current_pair_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.CreateModel(
            name='DecisionHealthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('health', models.CharField(choices=[('UNCHANGED', 'Unchanged'), ('EVIDENCE_CHANGED', 'Evidence_Changed'), ('PARTNER_UNAVAILABLE', 'Partner_Unavailable'), ('NEW_CANDIDATE', 'New_Candidate')], max_length=20)),
                ('attention', models.JSONField(default=list)),
                ('endpoints_available', models.BooleanField()),
                ('evidence_changed', models.BooleanField()),
                ('current_observation_ids', models.JSONField()),
                ('current_evidence_digest', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField()),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_snapshots', to='resolutions.decision')),
                ('decision_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_snapshots', to='resolutions.decisionrevision')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_health', to='reconciliation.reconciliationrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_health_snapshots', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'decision_health_snapshot',
            },
        ),
        migrations.CreateModel(
            name='CurrentDecisionHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('health', models.CharField(choices=[('UNCHANGED', 'Unchanged'), ('EVIDENCE_CHANGED', 'Evidence_Changed'), ('PARTNER_UNAVAILABLE', 'Partner_Unavailable'), ('NEW_CANDIDATE', 'New_Candidate')], max_length=20)),
                ('attention', models.JSONField(default=list)),
                ('applied_data_generation', models.PositiveBigIntegerField()),
                ('applied_resolution_generation', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField()),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_health', to='resolutions.decision')),
                ('decision_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_health', to='resolutions.decisionrevision')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_decision_health', to='reconciliation.reconciliationrun')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_decision_health', to='books.reconciliationscope')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_decision_health', to='workspaces.workspace')),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='current_projection', to='reconciliation.decisionhealthsnapshot')),
            ],
            options={
                'db_table': 'current_decision_health',
            },
        ),
        migrations.AddIndex(
            model_name='decisionhealthsnapshot',
            index=models.Index(fields=['workspace', 'decision', 'created_at'], name='health_snapshot_decision_idx'),
        ),
        migrations.AddConstraint(
            model_name='decisionhealthsnapshot',
            constraint=models.UniqueConstraint(fields=('run', 'decision_revision'), name='run_decision_health_unique'),
        ),
        migrations.AddConstraint(
            model_name='decisionhealthsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('health__in', ['UNCHANGED', 'EVIDENCE_CHANGED', 'PARTNER_UNAVAILABLE', 'NEW_CANDIDATE'])), name='decision_health_value_valid'),
        ),
        migrations.AddIndex(
            model_name='currentdecisionhealth',
            index=models.Index(fields=['workspace', 'scope', 'health'], name='current_health_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='currentdecisionhealth',
            constraint=models.UniqueConstraint(fields=('scope', 'decision'), name='scope_decision_health_unique'),
        ),
        migrations.AddConstraint(
            model_name='currentdecisionhealth',
            constraint=models.CheckConstraint(condition=models.Q(('health__in', ['UNCHANGED', 'EVIDENCE_CHANGED', 'PARTNER_UNAVAILABLE', 'NEW_CANDIDATE'])), name='current_decision_health_valid'),
        ),
    ]
