# Generated by Django 5.2.17 on 2026-09-08

from django.db import migrations, models


def backfill_run_progress(apps, schema_editor):
    run_model = apps.get_model("reconciliation", "ReconciliationRun")
    for run in run_model.objects.all().only("id", "lifecycle", "result_counts"):
        stage = {
            "COMPLETED": "COMPLETED",
            "FAILED": "FAILED",
            "RUNNING": "MATCHING",
        }.get(run.lifecycle, "QUEUED")
        counts = run.result_counts or {}
        run_model.objects.filter(id=run.id).update(
            progress_stage=stage,
            progress_counts=counts,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("reconciliation", "0003_remove_rundiagnostic_candidate_current_pair_observation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reconciliationrun",
            name="progress_counts",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="reconciliationrun",
            name="progress_stage",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("LOADING_INPUTS", "Loading inputs"),
                    ("MATCHING", "Matching"),
                    ("PUBLISHING", "Publishing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="QUEUED",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_run_progress, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="reconciliationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    progress_stage__in=[
                        "QUEUED",
                        "LOADING_INPUTS",
                        "MATCHING",
                        "PUBLISHING",
                        "COMPLETED",
                        "FAILED",
                    ]
                ),
                name="run_progress_stage_valid",
            ),
        ),
    ]
