# Generated by Django 5.2.17 on 2026-09-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_reconciliationscope_current_run'),
        ('ingestion', '0004_ingestionattempt_activation_reason'),
        ('reconciliation', '0004_reconciliationrun_progress'),
        ('workspaces', '0002_workspace_cleanup_and_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationrun',
            name='current_attempt_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='reconciliationrun',
            constraint=models.CheckConstraint(condition=models.Q(('lifecycle', 'RUNNING'), ('current_attempt_token__isnull', True), _connector='OR'), name='run_attempt_token_only_while_running'),
        ),
    ]
