# Generated by Django 5.2.17 on 2026-09-07 11:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_policyrevision_reconciliationscope_and_more'),
        ('ingestion', '0004_ingestionattempt_activation_reason'),
        ('workspaces', '0002_workspace_cleanup_and_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='books.reconciliationbook')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'decision',
            },
        ),
        migrations.CreateModel(
            name='DecisionRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('LINK', 'Link'), ('ACCEPT_UNMATCHED', 'Accept_Unmatched'), ('REJECT_CANDIDATE', 'Reject_Candidate'), ('REAFFIRM', 'Reaffirm'), ('REVOKE', 'Revoke'), ('REPLACE', 'Replace')], max_length=18)),
                ('authority_kind', models.CharField(blank=True, choices=[('LINK', 'Link'), ('ACCEPT_UNMATCHED', 'Accept_Unmatched'), ('REJECT_CANDIDATE', 'Reject_Candidate')], max_length=18, null=True)),
                ('record_side', models.CharField(blank=True, choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=5, null=True)),
                ('reason', models.TextField()),
                ('actor', models.CharField(max_length=80)),
                ('reviewed_observation_ids', models.JSONField(default=list)),
                ('reviewed_evidence_digest', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField()),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='resolutions.decision')),
                ('left_logical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decision_revisions_as_left', to='ingestion.logicaltransaction')),
                ('predecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor_revisions', to='resolutions.decisionrevision')),
                ('record_logical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decision_revisions_as_single', to='ingestion.logicaltransaction')),
                ('right_logical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decision_revisions_as_right', to='ingestion.logicaltransaction')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_revisions', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'decision_revision',
            },
        ),
        migrations.AddField(
            model_name='decision',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_decision', to='resolutions.decisionrevision'),
        ),
        migrations.CreateModel(
            name='ActiveDecisionClaim',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_decision_claims', to='books.reconciliationbook')),
                ('logical_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_decision_claims', to='ingestion.logicaltransaction')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_decision_claims', to='workspaces.workspace')),
                ('decision_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_claims', to='resolutions.decisionrevision')),
            ],
            options={
                'db_table': 'active_decision_claim',
            },
        ),
        migrations.CreateModel(
            name='DecisionSupersession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('replacement_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superseded_authorities', to='resolutions.decisionrevision')),
                ('superseded_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='resolutions.decisionrevision')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_supersessions', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'decision_supersession',
            },
        ),
        migrations.AddIndex(
            model_name='decisionrevision',
            index=models.Index(fields=['workspace', 'decision', 'revision'], name='rev_workspace_decision_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionrevision',
            index=models.Index(fields=['workspace', 'authority_kind'], name='revision_workspace_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='decisionrevision',
            constraint=models.UniqueConstraint(fields=('decision', 'revision'), name='decision_revision_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='decisionrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('predecessor__isnull', False)), fields=('predecessor',), name='decision_predecessor_successor_unique'),
        ),
        migrations.AddConstraint(
            model_name='decisionrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='decision_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='decisionrevision',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='decision_reason_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='decisionrevision',
            constraint=models.CheckConstraint(condition=models.Q(('actor', ''), _negated=True), name='decision_actor_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='decisionrevision',
            constraint=models.CheckConstraint(condition=models.Q(('left_logical', models.F('right_logical')), _negated=True), name='decision_pair_endpoints_distinct'),
        ),
        migrations.AddConstraint(
            model_name='decisionrevision',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['LINK', 'ACCEPT_UNMATCHED', 'REJECT_CANDIDATE', 'REAFFIRM', 'REVOKE', 'REPLACE'])), name='decision_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='decisionrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('authority_kind__in', ['LINK', 'REJECT_CANDIDATE']), ('left_logical__isnull', False), ('record_logical__isnull', True), ('record_side__isnull', True), ('right_logical__isnull', False)), models.Q(('authority_kind', 'ACCEPT_UNMATCHED'), ('left_logical__isnull', True), ('record_logical__isnull', False), ('record_side__in', ['LEFT', 'RIGHT']), ('right_logical__isnull', True)), models.Q(('action', 'REVOKE'), ('authority_kind__isnull', True), ('left_logical__isnull', True), ('record_logical__isnull', True), ('record_side__isnull', True), ('right_logical__isnull', True)), _connector='OR'), name='decision_authority_shape_valid'),
        ),
        migrations.AddConstraint(
            model_name='decisionrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'LINK'), ('authority_kind', 'LINK')), models.Q(('action', 'ACCEPT_UNMATCHED'), ('authority_kind', 'ACCEPT_UNMATCHED')), models.Q(('action', 'REJECT_CANDIDATE'), ('authority_kind', 'REJECT_CANDIDATE')), models.Q(('action__in', ['REAFFIRM', 'REPLACE']), ('authority_kind__in', ['LINK', 'ACCEPT_UNMATCHED', 'REJECT_CANDIDATE'])), models.Q(('action', 'REVOKE'), ('authority_kind__isnull', True)), _connector='OR'), name='decision_action_authority_valid'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['workspace', 'book', 'created_at', 'id'], name='decision_workspace_book_idx'),
        ),
        migrations.AddIndex(
            model_name='activedecisionclaim',
            index=models.Index(fields=['workspace', 'book', 'decision_revision'], name='claim_workspace_book_idx'),
        ),
        migrations.AddConstraint(
            model_name='activedecisionclaim',
            constraint=models.UniqueConstraint(fields=('book', 'logical_transaction'), name='active_claim_book_logical_unique'),
        ),
        migrations.AddConstraint(
            model_name='activedecisionclaim',
            constraint=models.UniqueConstraint(fields=('decision_revision', 'logical_transaction'), name='active_claim_revision_logical_unique'),
        ),
        migrations.AddIndex(
            model_name='decisionsupersession',
            index=models.Index(fields=['workspace', 'superseded_revision'], name='supersession_workspace_idx'),
        ),
        migrations.AddConstraint(
            model_name='decisionsupersession',
            constraint=models.UniqueConstraint(fields=('replacement_revision', 'superseded_revision'), name='decision_supersession_unique'),
        ),
        migrations.AddConstraint(
            model_name='decisionsupersession',
            constraint=models.CheckConstraint(condition=models.Q(('replacement_revision', models.F('superseded_revision')), _negated=True), name='decision_supersession_not_self'),
        ),
    ]
