# Generated by Django 5.2.17 on 2026-09-06 07:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('workspaces', '0002_workspace_cleanup_and_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('mapping', models.JSONField()),
                ('parser_version', models.CharField(max_length=40)),
                ('digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_revisions', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'mapping_revision',
            },
        ),
        migrations.CreateModel(
            name='SourceSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('adapter_key', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'source_system',
            },
        ),
        migrations.CreateModel(
            name='SourceContractRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('mode', models.CharField(choices=[('FULL_SNAPSHOT', 'Full_Snapshot'), ('DELTA', 'Delta')], max_length=13)),
                ('timezone_name', models.CharField(blank=True, max_length=80, null=True)),
                ('identity_namespace', models.CharField(max_length=160)),
                ('reference_semantics', models.CharField(choices=[('TRUSTED_SHARED', 'Trusted_Shared'), ('SECONDARY', 'Secondary'), ('NONE', 'None')], max_length=14)),
                ('contract', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField()),
                ('mapping_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='sources.mappingrevision')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_revisions', to='workspaces.workspace')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_revisions', to='sources.sourcesystem')),
            ],
            options={
                'db_table': 'source_contract_revision',
            },
        ),
        migrations.AddField(
            model_name='mappingrevision',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapping_revisions', to='sources.sourcesystem'),
        ),
        migrations.CreateModel(
            name='BookSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=5)),
                ('identity_namespace', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_sources', to='books.reconciliationbook')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_sources', to='workspaces.workspace')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_sources', to='sources.sourcesystem')),
            ],
            options={
                'db_table': 'book_source',
            },
        ),
        migrations.AddIndex(
            model_name='sourcesystem',
            index=models.Index(fields=['workspace', 'name'], name='source_workspace_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcesystem',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='source_name_nonempty'),
        ),
        migrations.AddIndex(
            model_name='sourcecontractrevision',
            index=models.Index(fields=['workspace', 'source'], name='contract_workspace_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcecontractrevision',
            constraint=models.UniqueConstraint(fields=('source', 'revision'), name='contract_source_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='sourcecontractrevision',
            constraint=models.CheckConstraint(condition=models.Q(('identity_namespace', ''), _negated=True), name='contract_namespace_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='sourcecontractrevision',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ['FULL_SNAPSHOT', 'DELTA'])), name='contract_valid_mode'),
        ),
        migrations.AddConstraint(
            model_name='sourcecontractrevision',
            constraint=models.CheckConstraint(condition=models.Q(('reference_semantics__in', ['TRUSTED_SHARED', 'SECONDARY', 'NONE'])), name='contract_valid_reference'),
        ),
        migrations.AddIndex(
            model_name='mappingrevision',
            index=models.Index(fields=['workspace', 'source'], name='mapping_workspace_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='mappingrevision',
            constraint=models.UniqueConstraint(fields=('source', 'revision'), name='mapping_source_revision_unique'),
        ),
        migrations.AddIndex(
            model_name='booksource',
            index=models.Index(fields=['workspace', 'book'], name='book_source_workspace_idx'),
        ),
        migrations.AddConstraint(
            model_name='booksource',
            constraint=models.UniqueConstraint(fields=('book', 'role'), name='book_source_role_unique'),
        ),
        migrations.AddConstraint(
            model_name='booksource',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['LEFT', 'RIGHT'])), name='book_source_valid_role'),
        ),
        migrations.AddConstraint(
            model_name='booksource',
            constraint=models.CheckConstraint(condition=models.Q(('identity_namespace', ''), _negated=True), name='book_source_namespace_nonempty'),
        ),
    ]
